version: '2'
services:
  server:
    image: node-server
    hostname: node-server
    expose:
      - 8080
    ports:
      - "80:8080"
    links:
      - database
    container_name: nodejs-service
  database:
    image: node-db
    hostname: postgres-db
    expose:
      - 5432
    container_name: postgres-service
